### ISSUE TITLE
Images are broken on the SDKs/Tools Page

### ISSUE THREAD

**Issue by kevineger** [MicrosoftDocs/healthvault-docs#30]
![image](https://user-images.githubusercontent.com/6925321/28079307-ac758e5c-661c-11e7-990e-9a19f25d91cb.png)

Images are coming from an unreadable source.

**Comment by jhutchings1** [comment]
Thanks for letting me know, Kevin. The images on our site are actually part of a separate docs page (/media), so it's possible there was an intermittent issue with their page. If we see it again, I can escalate to the docs team for investigation. At the moment, there's no repro on the issue, so I don't think we can make much headway on it.
